version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    volumes:
      - ./:/var/www
      - /var/www/node_modules
    ports:
      - "3000:3000"
    tty: true
    restart: always
