version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    environment:
      - MY_LIFF_ID={MY_LIFF_ID}
      - API_URL={API_URL}
    volumes:
      - ./:/var/www
      - /var/www/node_modules
    ports:
      - "3000:3000"
    tty: true
    restart: always
